from typing import Protocol, Any


class CalendarRepositoryProtocol(Protocol):
    async def create_event(self, data: dict[str, Any]) -> dict[str, Any]: ...
    async def get_event(self, event_id: str) -> dict[str, Any] | None: ...
    async def list_events(self, from_date: str | None = None, to_date: str | None = None, limit: int = 50) -> list[dict[str, Any]]: ...
    async def update_event(self, event_id: str, data: dict[str, Any]) -> dict[str, Any] | None: ...
    async def delete_event(self, event_id: str) -> bool: ...

    async def create_reminder(self, data: dict[str, Any]) -> dict[str, Any]: ...
    async def get_reminder(self, reminder_id: str) -> dict[str, Any] | None: ...
    async def list_reminders(self, status: str | None = None, limit: int = 50) -> list[dict[str, Any]]: ...
    async def update_reminder(self, reminder_id: str, data: dict[str, Any]) -> dict[str, Any] | None: ...
    async def delete_reminder(self, reminder_id: str) -> bool: ...
    async def get_due_reminders(self) -> list[dict[str, Any]]: ...
    async def mark_reminder_triggered(self, reminder_id: str) -> dict[str, Any] | None: ...

    async def create_notification(self, data: dict[str, Any]) -> dict[str, Any]: ...
    async def list_notifications(self, status: str | None = None, limit: int = 50) -> list[dict[str, Any]]: ...
    async def mark_notification_sent(self, notification_id: str) -> dict[str, Any] | None: ...