from typing import Any


class NotificationRepositoryProtocol:
    async def create(self, data: dict[str, Any]) -> dict[str, Any]: ...
    async def list(self, importance: str | None = None, limit: int = 50) -> list[dict[str, Any]]: ...
    async def create_alert(self, data: dict[str, Any]) -> dict[str, Any]: ...
    async def list_alerts(self, status: str | None = None) -> list[dict[str, Any]]: ...
    async def acknowledge_alert(self, alert_id: str) -> dict[str, Any] | None: ...