from typing import Protocol, Any


class TaskRepositoryProtocol(Protocol):
    async def create(self, data: dict[str, Any]) -> dict[str, Any]: ...
    async def get(self, task_id: str) -> dict[str, Any] | None: ...
    async def list(self, status: str | None = None, limit: int = 50) -> list[dict[str, Any]]: ...
    async def update(self, task_id: str, data: dict[str, Any]) -> dict[str, Any] | None: ...
    async def delete(self, task_id: str) -> bool: ...