from typing import Protocol, Any


class MemoryRepositoryProtocol(Protocol):
    async def create(self, data: dict[str, Any]) -> dict[str, Any]: ...
    async def get(self, memory_id: str) -> dict[str, Any] | None: ...
    async def list(self, limit: int = 50) -> list[dict[str, Any]]: ...
    async def search(self, query: str, limit: int = 10) -> list[dict[str, Any]]: ...
    async def delete(self, memory_id: str) -> bool: ...
    async def save_conversation(self, data: dict[str, Any]) -> dict[str, Any]: ...