from typing import Any


class ActionRepositoryProtocol:
    async def create(self, data: dict[str, Any]) -> dict[str, Any]: ...
    async def update(self, action_id: str, data: dict[str, Any]) -> dict[str, Any] | None: ...
    async def list(self, status: str | None = None, limit: int = 50) -> list[dict[str, Any]]: ...
    async def get(self, action_id: str) -> dict[str, Any] | None: ...